### ISSUE TITLE
nofail option problems

### ISSUE THREAD

**Issue by SlowLogicBoy** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#36] opened 2020-02-22 09:53 UTC
Hey,

I don't know really know where to write this issue so I'm starting here so you might point me to the right direction.

My HDDs are encrypted with luks (through plugin)
And I merged those HDDs through unionfs (this plugin)

Because of encryption, I must provide `nofail` option for unionfs mount point, otherwise system is not booting (I also specified `x-systemd.device-timeout=1`), however `fuse.mergerfs` (or `libfuse` itself) doesn't recognize this option and because of that, it throws an exception while I apply configuration changes, which contains `fuse: unknown option `nofail'` full exception can be found [here](https://gist.github.com/SlowLogicBoy/ca980557834c4b5e410b31f4c09aefb6)

that's why I save it without `nofail` option and edit `/etc/fstab` manually.

Do you guys have a solution for this?

**Comment by subzero79** [comment] 2020-02-22 11:03
This is a saltstack issue apparently, which is core now in omv. 

https://github.com/systemd/systemd/issues/5032

Haven’t check but comments said also fuse fixed that upstream. I remember using nofail in omv4 without issues. 

Solution is for you to maintain your own systemd unit for your mergerfs point and use the sharedrootfs plugin to be able to use the point in services.

**Comment by snow3461** [comment] 2020-04-20 12:10
Quick workaround I found to this problem :
`apt install fuse3`

Then you can use **nofail** options.

I don't know yet if there is any side-effect. Debian chosed fuse 2.x, , they may be a reason....

**Comment by ryecoaaron** [comment] 2020-04-20 12:30
Strange.  I will have to test that.  mergerfs includes its own fuse code.  So, the system installed version shouldn't matter.

**Comment by mrreview** [comment] 2020-12-19 20:45
Hello, I'm facing similar problem, when using mount -a command throws the same error.. is it safe to install fuse3 without any side-effects? Thank you

**Comment by gderf** [comment] 2020-12-19 22:54
I am on OMV 5.5.19-1 and I installed fuse3 as suggested. This is the output, but I do not know yet if anything was broken when fuse was removed. mount-a works now though.

fred@omv:~$ sudo apt install fuse3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libfuse3-3
The following packages will be REMOVED:
  fuse
The following NEW packages will be installed:
  fuse3 libfuse3-3
0 upgraded, 2 newly installed, 1 to remove and 2 not upgraded.
Need to get 114 kB of archives.
After this operation, 246 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ftp.us.debian.org/debian buster/main amd64 libfuse3-3 amd64 3.4.1-1+deb10u1 [81.2 kB]
Get:2 http://ftp.us.debian.org/debian buster/main amd64 fuse3 amd64 3.4.1-1+deb10u1 [32.8 kB]
Fetched 114 kB in 0s (298 kB/s)  
Selecting previously unselected package libfuse3-3:amd64.
(Reading database ... 270473 files and directories currently installed.)
Preparing to unpack .../libfuse3-3_3.4.1-1+deb10u1_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.4.1-1+deb10u1) ...
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.
 mergerfs depends on fuse.
 borgbackup depends on fuse.

**Comment by ryecoaaron** [comment] 2020-12-19 22:58
As mention in my previous post, mergerfs includes its own fuse code. so, the system’s fuse version doesn’t matter.

**Comment by gderf** [comment] 2020-12-19 23:14
What about the other two packages that depend on fuse which was removed, **ntfs-3g** and **borgbackup**?

**Comment by ryecoaaron** [comment] 2020-12-19 23:28
I would imagine they do not work with fuse3

**Comment by gderf** [comment] 2020-12-19 23:50
I don't use borgbackup, so I can't say one way or the other.  I can't remember the last time I plugged an ntfs formatted drive into OMV, but I do remember needing to do that at the time. But if that gets broken I can live without it easily. Not sure how others will fare.

**Comment by ryecoaaron** [comment] 2020-12-19 23:59
ntfs-3g is a dependency of omv itself. So if installing fuse3 uninstalls ntfs-3g, it will uninstall omv too.

**Comment by gderf** [comment] 2020-12-20 00:12
I think you misread me. fuse was uninstalled, but not the identified programs that depend on it. The question is did removing fuse break these programs that depend on it or not? mergerfs still works, but as you said it provides its own fuse code.

**Comment by ryecoaaron** [comment] 2020-12-20 00:32
not sure. I’ve never tried. Looks like they work with either version of fuse from their dependencies.

**Comment by snow3461** [comment] 2020-12-20 10:15
@ryecoaaron well, from my experience, I see a difference. Either 'nofail' flag doesn't work (with fuse) or it works as intended (with fuse-3), again on a mergers mount, obviously .

**Comment by ryecoaaron** [comment] 2020-12-20 14:33
That would be something for the mergerfs dev to explain (trapexit).

**Closed** 2022-03-30 17:40 UTC
